### ISSUE TITLE
On fresh install of latest build, it didnt ask for bt perms

### ISSUE THREAD

**Issue by MasterTailer** [OpenTails/tail_app#203]
It was a fresh install - perhaps it didnt need them? But I expected it to - buttons are greyed

I could continue, and all worked! So perhaps this is intentional as the app had perms from previous installs?

![photo_2024-06-03_06-28-35](https://github.com/OpenTails/tail_app/assets/44520040/9ffaff9f-26e1-483c-bdc6-abb3c4182ee7)

**Comment by MasterTailer** [comment]
The second time I ran it, it asked me for perms before the onboarding. In both cases, everything worked afterwards. So this might not be a thing

**Comment by Codel1417** [comment]
I suspect you tapped the allow button by accident. The Bluetooth check is local to onboarding and only clears once the button is pressed or bt permission is accepted beforehand
