### ISSUE TITLE
We need a "connect to all" when multiple devices are listed in the connection window

### ISSUE THREAD

**Issue by MasterTailer** [OpenTails/tail_app#214]

**Comment by ToeiRei** [comment]
I would recommend something along the lines of 'connect to KNOWN devices' as well as I do not want to attempt to connect to the 200 tails found on a con floor

**Comment by MasterTailer** [comment]
Yeah ok I see your point

**Comment by Codel1417** [comment]
> I would recommend something along the lines of 'connect to KNOWN devices' as well as I do not want to attempt to connect to the 200 tails found on a con floor

From experimenting with my own gear on 2 devices, gear connected to a phone is not discoverable by other phones

**Comment by MasterTailer** [comment]
Very true - i guess is the edge  case of lots of unconnected gear in your vicinity. Perhaps a convention, although its usually paired and moving..

**Comment by Codel1417** [comment]
adding the button but hiding it behind dev mode
